#!/bin/bash

echo "🚀 Deploying CIRCLE Backend to Railway"
echo ""
echo "Step 1: Push to GitHub"
echo "====================="
echo ""
echo "1. Go to: https://github.com/new"
echo "2. Repository name: circle-app"
echo "3. Make it PRIVATE"
echo "4. Click 'Create repository'"
echo ""
echo "5. Copy YOUR repository URL and run:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/circle-app.git"
echo "   git push -u origin main"
echo ""
echo "Step 2: Deploy to Railway"
echo "========================="
echo ""
echo "1. Go to: https://railway.app"
echo "2. Sign in with GitHub"
echo "3. Click 'New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose 'circle-app'"
echo "6. Railway will auto-deploy!"
echo ""
echo "Step 3: Add Database"
echo "===================="
echo ""
echo "1. In Railway project, click '+ New'"
echo "2. Select 'Database' → 'PostgreSQL'"
echo "3. Click '+ New' again"
echo "4. Select 'Database' → 'Redis'"
echo ""
echo "Step 4: Configure Backend"
echo "========================="
echo ""
echo "1. Click on your backend service"
echo "2. Go to 'Variables' tab"
echo "3. Add these:"
echo "   - NODE_ENV=production"
echo "   - AGORA_APP_ID=3605bccbfb3546ccae9de1c36dfd4ebd"
echo ""
echo "4. Railway auto-connects DATABASE_URL and REDIS_URL!"
echo ""
echo "Step 5: Get Your URL"
echo "===================="
echo ""
echo "1. Click 'Settings' tab"
echo "2. Click 'Generate Domain'"
echo "3. Copy the URL (e.g., https://circle-app-production.up.railway.app)"
echo ""
echo "Step 6: Update Mobile App"
echo "=========================="
echo ""
echo "Edit: mobile-app/src/services/api.service.ts"
echo ""
echo "Change:"
echo "  const API_BASE_URL = 'http://192.168.29.43:3000';"
echo ""
echo "To:"
echo "  const API_BASE_URL = 'https://YOUR-RAILWAY-URL.up.railway.app';"
echo ""
echo "Step 7: Build APK"
echo "================="
echo ""
echo "  cd mobile-app"
echo "  eas build --profile preview --platform android"
echo ""
echo "✅ DONE! Voice calls will work!"
echo ""
